//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Recursos {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Mensagens {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Mensagens() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Recursos.Mensagens", typeof(Mensagens).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ano não permitido.
        /// </summary>
        public static string AnoNaoPermitido {
            get {
                return ResourceManager.GetString("AnoNaoPermitido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cliente Não Encontrada.
        /// </summary>
        public static string ClienteNaoEncontrado {
            get {
                return ResourceManager.GetString("ClienteNaoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Conta Não Encontrada.
        /// </summary>
        public static string ContaNaoEncontrada {
            get {
                return ResourceManager.GetString("ContaNaoEncontrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a É necessário informar os dados da conta para a criação.
        /// </summary>
        public static string ContaNaoInformada {
            get {
                return ResourceManager.GetString("ContaNaoInformada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Conta Removida.
        /// </summary>
        public static string ContaRemovida {
            get {
                return ResourceManager.GetString("ContaRemovida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cpf Não pode ser nulo.
        /// </summary>
        public static string CpfNaoNulo {
            get {
                return ResourceManager.GetString("CpfNaoNulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Data de Nascimento não pode ser nula.
        /// </summary>
        public static string DataNascimentoNaoNula {
            get {
                return ResourceManager.GetString("DataNascimentoNaoNula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Excluído com Sucesso.
        /// </summary>
        public static string ExcluidoComSucesso {
            get {
                return ResourceManager.GetString("ExcluidoComSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a É necessário criar um cliente e adicionar nessa requisição.
        /// </summary>
        public static string FaltaCliente {
            get {
                return ResourceManager.GetString("FaltaCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Você não tem idade para ter conta bancária.
        /// </summary>
        public static string MenorDeIdade {
            get {
                return ResourceManager.GetString("MenorDeIdade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Essa Pessoa não pode ser removida.
        /// </summary>
        public static string NaoPodeExcluir {
            get {
                return ResourceManager.GetString("NaoPodeExcluir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Pessoa Não Criada.
        /// </summary>
        public static string PessoaNaoCriada {
            get {
                return ResourceManager.GetString("PessoaNaoCriada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A primeira letra deve ser maiúscula.
        /// </summary>
        public static string PrimeiraLetraMaiuscula {
            get {
                return ResourceManager.GetString("PrimeiraLetraMaiuscula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Transacao Não Criada.
        /// </summary>
        public static string TransacaoNaoCriada {
            get {
                return ResourceManager.GetString("TransacaoNaoCriada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Transacao Não Encontrada.
        /// </summary>
        public static string TransacaoNaoEncontrada {
            get {
                return ResourceManager.GetString("TransacaoNaoEncontrada", resourceCulture);
            }
        }
    }
}
